name: cypher_sheet
description: A little fun project for a Cypher Character Sheet built in Flutter
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.13+2

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.0
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.2
  protobuf: ^2.1.0
  path_provider: ^2.0.11
  path: ^1.8.2
  uuid: ^3.0.7
  json_diff: ^0.2.1
  flutter_colorpicker: ^1.0.3
  share_plus: ^6.3.1
  file_picker: ^5.2.5
  flutter_markdown: ^0.6.14
  url_launcher: ^6.1.10
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  flutter_oss_licenses: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - icons/
